# gen-cargo.ps1
# Generates the Cargo.toml from root, creating a [[bin]] for every problems/*.rs.
# This is what rust-analyzer needs to "see" every problem and gives you autocomplete
# It is called by build-current.ps1 each time you compile .rs, so it's never outdated

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$toml = Join-Path $root "Cargo.toml"

# Fixed header of the package
$lines = 
@(
    '[package]'
    'name = "AYDAStudy"'
    'version = "0.1.0"'
    'edition = "2021"'
    'autobins = false'
    ''
    '[dependencies]'
    ''
    '# --- BINARIES (one per problem). Do NOT edit manually: it is generated by gen-cargo.ps1 ---'
)

# A [[bin]] for every .rs inside of problems/ 
Get-ChildItem -Path (Join-Path $root "Problems") -Filter *.rs | Sort-Object Name | ForEach-Object {
    $name = $_.BaseName
    $path = $_.FullName.Substring($root.Length + 1) -replace '\\', '/'
    $lines += '[[bin]]'
    $lines += "name = `"$name`""
    $lines += "path = `"$path`""
    $lines += ''
}
Get-ChildItem -Path (Join-Path $root "AYDAConcepts") -Filter *.rs | Sort-Object Name | ForEach-Object {
    $name = $_.BaseName
    $path = $_.FullName.Substring($root.Length + 1) -replace '\\', '/'
    $lines += '[[bin]]'
    $lines += "name = `"$name`""
    $lines += "path = `"$path`""
    $lines += ''
}

Set-Content -Path $toml -Value $lines -Encoding utf8
Write-Host "Cargo.toml generated ($((Get-ChildItem (Join-Path $root 'problems') -Filter *.rs).Count) binaries)"
